power_analysis:
  # a list of input feature names (comma separated) used to aggregate results. Leave blank if not used
  group_by:
  # a list of metrics (comma separated) to be used in the stat. analysis
  metrics:
  power: 0.9
  pvalue: 0.1